import { query } from '../config/database';
import { FeeStatus } from '../types';

/**
 * Billing Service
 *
 * Auto-generates fee records for a student's per-student enrollment:
 *  - An initial fee the moment an enrollment with a monthlyFee + startDate is created
 *    (prorated for the remaining sessions in the starting month, or the full amount if
 *    no timing template is set or the student starts on the month's first session day).
 *  - A recurring full-month fee for every subsequent month the enrollment stays active,
 *    generated by a daily cron hitting generateMonthlyFees() — idempotent, so running it
 *    more than once (or every day) never creates duplicates for the same student+month.
 */

const DAY_OF_WEEK_MAP: Record<string, number> = {
  Sun: 0, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6,
};

function formatDateLocal(d: Date): string {
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function parseDateLocal(dateStr: string): Date {
  const [year, month, day] = dateStr.split('-').map(Number);
  return new Date(year, month - 1, day);
}

/** Count how many dates in [from, to] (inclusive, local calendar days) match a set of weekdays. */
function countMatchingDays(from: Date, to: Date, weekdays: Set<number>): number {
  if (weekdays.size === 0) return 0;
  let count = 0;
  const cursor = new Date(from);
  cursor.setHours(0, 0, 0, 0);
  const end = new Date(to);
  end.setHours(0, 0, 0, 0);
  while (cursor <= end) {
    if (weekdays.has(cursor.getDay())) count++;
    cursor.setDate(cursor.getDate() + 1);
  }
  return count;
}

/**
 * Computes total sessions across the whole month containing `startDate`, and the sessions
 * remaining from startDate (inclusive) through the end of that month, based on a timing
 * template's session_slots weekdays. Returns nulls if the template has no valid slots.
 */
async function computeMonthSessionCounts(
  templateId: string,
  startDate: Date
): Promise<{ totalSessions: number; remainingSessions: number } | null> {
  const slotsResult = await query(
    `SELECT DISTINCT day_of_week FROM session_slots WHERE template_id = $1`,
    [templateId]
  );
  if (slotsResult.rows.length === 0) return null;

  const weekdays = new Set<number>();
  for (const row of slotsResult.rows) {
    const num = DAY_OF_WEEK_MAP[row.day_of_week];
    if (num !== undefined) weekdays.add(num);
  }
  if (weekdays.size === 0) return null;

  const monthStart = new Date(startDate.getFullYear(), startDate.getMonth(), 1);
  const monthEnd = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0);

  const totalSessions = countMatchingDays(monthStart, monthEnd, weekdays);
  const remainingSessions = countMatchingDays(startDate, monthEnd, weekdays);

  return { totalSessions, remainingSessions };
}

/** Last calendar day of the month containing `date`. */
function lastDayOfMonth(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth() + 1, 0);
}

/** 10th of the month containing `date` (standard due date for recurring monthly fees). */
function tenthOfMonth(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), 10);
}

function monthYearOf(date: Date): string {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
}

async function feeExistsForMonth(studentId: string, monthYear: string): Promise<boolean> {
  const result = await query(
    `SELECT 1 FROM fee_records WHERE student_id = $1 AND month_year = $2 LIMIT 1`,
    [studentId, monthYear]
  );
  return result.rows.length > 0;
}

export interface GenerateInitialFeeParams {
  studentId: string;
  monthlyFee: number | null;
  startDate: string; // YYYY-MM-DD
  batchTimeTemplateId: string | null;
  centerId: string | null;
}

/**
 * Creates the student's first fee record the moment an enrollment with a monthly fee is
 * created — prorated to the sessions remaining in the starting month when a timing template
 * is set, otherwise the full monthly amount. No-ops (does not throw) if monthlyFee is missing/
 * zero or a fee already exists for that student+month, so it's safe to call on every
 * enrollment change including no-op re-saves.
 */
export async function generateInitialFeeForEnrollment(params: GenerateInitialFeeParams): Promise<void> {
  const { studentId, monthlyFee, startDate, batchTimeTemplateId, centerId } = params;
  if (monthlyFee == null || monthlyFee <= 0) return;

  const start = parseDateLocal(startDate);
  const monthYear = monthYearOf(start);

  if (await feeExistsForMonth(studentId, monthYear)) return;

  let amount = monthlyFee;
  let notes = 'Initial enrollment fee — auto-generated';

  if (batchTimeTemplateId) {
    const counts = await computeMonthSessionCounts(batchTimeTemplateId, start);
    if (counts && counts.totalSessions > 0 && counts.remainingSessions < counts.totalSessions) {
      amount = Math.round((monthlyFee / counts.totalSessions) * counts.remainingSessions * 100) / 100;
      notes = `Prorated enrollment fee — ${counts.remainingSessions} of ${counts.totalSessions} sessions remaining in ${monthYear}`;
    }
  }

  if (amount <= 0) return;

  await query(
    `INSERT INTO fee_records (student_id, amount, month_year, due_date, status, notes, center_id)
     VALUES ($1, $2, $3, $4, $5, $6, $7)`,
    [studentId, amount, monthYear, formatDateLocal(lastDayOfMonth(start)), FeeStatus.PENDING, notes, centerId]
  );
}

export interface MonthlyFeeGenerationResult {
  created: number;
  skipped: number;
  errors: Array<{ studentId: string; message: string }>;
}

/**
 * Recurring monthly billing run — for every student with an active enrollment carrying a
 * monthly fee, ensures a fee record exists for the current month (skipping students whose
 * enrollment started this same month, since generateInitialFeeForEnrollment already covered
 * it, and skipping any student who already has one). Idempotent by construction, so re-running
 * it — including every day within the same month, or for the same center twice — is always
 * safe. Pass centerId to scope a manual, per-tenant trigger; omit it to process every center at
 * once (the daily cron).
 */
export async function generateMonthlyFees(centerId?: string): Promise<MonthlyFeeGenerationResult> {
  const today = new Date();
  const currentMonthYear = monthYearOf(today);
  const dueDate = formatDateLocal(tenthOfMonth(today));

  const result: MonthlyFeeGenerationResult = { created: 0, skipped: 0, errors: [] };

  const activeEnrollments = await query(
    `SELECT e.student_id, e.monthly_fee, e.start_date, s.center_id
     FROM student_enrollments e
     JOIN students s ON s.id = e.student_id
     WHERE e.status = 'active'
       AND e.monthly_fee IS NOT NULL
       AND e.monthly_fee > 0
       AND s.status != 'archived'
       ${centerId ? 'AND s.center_id = $1' : ''}`,
    centerId ? [centerId] : []
  );

  for (const row of activeEnrollments.rows) {
    try {
      const startDate = new Date(row.start_date);
      // Enrollments starting this month are handled by generateInitialFeeForEnrollment, not here.
      // Enrollments starting in a future month (marked 'active' ahead of their actual start date,
      // e.g. a batch assignment made before the term begins) aren't due for a fee yet at all.
      if (monthYearOf(startDate) >= currentMonthYear) {
        result.skipped++;
        continue;
      }

      if (await feeExistsForMonth(row.student_id, currentMonthYear)) {
        result.skipped++;
        continue;
      }

      await query(
        `INSERT INTO fee_records (student_id, amount, month_year, due_date, status, notes, center_id)
         VALUES ($1, $2, $3, $4, $5, $6, $7)`,
        [
          row.student_id,
          row.monthly_fee,
          currentMonthYear,
          dueDate,
          FeeStatus.PENDING,
          'Monthly fee — auto-generated',
          row.center_id,
        ]
      );
      result.created++;
    } catch (err) {
      result.errors.push({
        studentId: row.student_id,
        message: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return result;
}
